title: "Fabian M端ller, PhD"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Grundlegende Einstellungen
name: "Fabian M端ller"
description: "Social psychologist working at the intersection of education, inequality, and policy."
locale: "en"

# Navigation (Header oben)
header:
  background: "#111"
  text_color: "#fff"
  logo: false
  title: "Fabian M端ller, PhD"
  nav:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv/
    - title: "Research"
      url: /research/
    - title: "Contact"
      url: /contact/

footer:
  text: ""
  background: "#111"
  text_color: "#cccccc"
  links: []
  powered_by: false



# Plugins (wichtig f端r Navigation etc.)
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap

# Sass (damit dein eigenes CSS greift)
sass:
  style: compressed

# Custom CSS (falls du eigene CSS-Datei einbindest)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"

atom_feed:
  hide: true

